load_test_db()
test_that("gtrack.var works", {
    expect_regression(gtrack.var.get("test.fixedbin", "pv.percentiles"), "test.fixedbin.pv.percentiles")
    expect_error(gtrack.var.get("test.fixedbin", "blablablabla"))
    expect_error(gtrack.var.get("test.blablablabla", "pv.percentiles"))
    expect_equal(gtrack.var.ls("test.fixedbin"), "pv.percentiles")
    expect_error(gtrack.var.ls("test.blablablabla"))
})

test_that("gtrack.var.set works", {
    track_name <- random_track_name()
    gtrack.rm(track_name, force = TRUE)
    withr::defer(gtrack.rm(track_name, force = TRUE))
    gtrack.create_sparse(track_name, "", gintervals(c(1, 2)), 1:2)
    gtrack.var.set(track_name, "testvar1", 1)
    gtrack.var.set(track_name, "testvar2", 1)
    r1 <- gtrack.var.ls(track_name)
    gtrack.var.rm(track_name, "testvar2")
    r2 <- gtrack.var.ls(track_name)
    expect_equal(list(r1, r2), list(c("testvar1", "testvar2"), "testvar1"))
})

test_that("gtrack.rm works", {
    track_name <- random_track_name()
    expect_warning(gtrack.var.rm("test.fixedbin", "blablablabla"))
    expect_error(gtrack.var.rm("test.blablablabla", "pv.percentiles"))
    gtrack.rm(track_name, force = TRUE)
    withr::defer(gtrack.rm(track_name, force = TRUE))
    gtrack.create_sparse(track_name, "", gintervals(c(1, 2)), 1:2)
    gtrack.var.set(track_name, "testvar1", 1:10)
    r1 <- gtrack.var.get(track_name, "testvar1")
    gtrack.var.set(track_name, "testvar1", 21:30)
    r2 <- gtrack.var.get(track_name, "testvar1")
    expect_equal(list(r1, r2), list(1:10, 21:30))

    expect_error(gtrack.var.set("test.blablablabla", "testvar1", 1:10))
})
