gtrack.var.get("test.fixedbin", "pv.percentiles")
gtrack.var.get("test.fixedbin", "blablablabla")
gtrack.var.get("test.blablablabla", "pv.percentiles")
gtrack.var.ls("test.fixedbin")
gtrack.var.ls("test.blablablabla")
{
    gtrack.rm("test.tmptrack", force=T)
    gtrack.create_sparse("test.tmptrack", "", gintervals(c(1,2)), 1 : 2)
    gtrack.var.set("test.tmptrack", "testvar1", 1)
    gtrack.var.set("test.tmptrack", "testvar2", 1)
    r1 <- gtrack.var.ls("test.tmptrack")
    gtrack.var.rm("test.tmptrack", "testvar2")
    r2 <- gtrack.var.ls("test.tmptrack")
    gtrack.rm("test.tmptrack", force=T)
    list(r1, r2)
}
gtrack.var.rm("test.fixedbin", "blablablabla")
gtrack.var.rm("test.blablablabla", "pv.percentiles")
{
    gtrack.rm("test.tmptrack", force=T)
    gtrack.create_sparse("test.tmptrack", "", gintervals(c(1,2)), 1 : 2)
    gtrack.var.set("test.tmptrack", "testvar1", 1:10)
    r1 <- gtrack.var.get("test.tmptrack", "testvar1")
    gtrack.var.set("test.tmptrack", "testvar1", 21:30)
    r2 <- gtrack.var.get("test.tmptrack", "testvar1")
    gtrack.rm("test.tmptrack", force=T)
    list(r1, r2)
}
gtrack.var.set("test.blablablabla", "testvar1", 1:10)